### ISSUE TITLE
Missing Features..?..

### ISSUE THREAD

**Issue by corneliusabel** [Ecodev/natural-gallery-js#62]
First of all, really great gallery!!!
I used it with a django backend to serve and display photo in my home cloud.

However, Iam missing two features:
First i would like to know which items are currently displayed on the screen (not in the DOM outside the screen) to present some extra info like a date range. Is there a function like getVisibleItems() which gives you an arry of the displayed items, or how can that be achived??

Second i would like to jump (scroll) to a certain image (which has not necessarly been loaded). Is there a way to calculate the position and do some _scrollTop_ so it??

Best,

Cornelius

**Comment by sambaptista** [comment]
Hi ! Thanks for your feedback ! Glad you like it.

> First i would like to know which items are currently displayed on the screen (not in the DOM outside the screen) to present some extra info like a date range. Is there a function like getVisibleItems() which gives you an arry of the displayed items, or how can that be achived??

There's no such method to get this, but there is an event emitted when an image is added to the DOM  https://ecodev.github.io/natural-gallery-js/docs-api.html > events > item-added-to-dom. 

It's not a perfect method because you have to build your own list by listing the events and then keep it up to date (that means, for example, reset it in case of a new search that resets the list).

The method you mentions definitely deserves to be implemented, I add it to the todos.

> Second i would like to jump (scroll) to a certain image (which has not necessarily been loaded). Is there a way to calculate the position and do some scrollTop so it??

I would say this is not something that should be included in the gallery because the navigation is part of the consuming application.  For example : the element that triggers the scroll action does not belong to the gallery. It's something external in your own GUI. Furthermore, the management of the scroll may depend on many factors (the scrollElement can contain more than just the gallery). Manipulate the scroll from the gallery can be too much intrusive for some use cases and it's better to provide full control to the developer of the parent app.

For those reasons, I don't think it's relevant to implement such feature. 

At this point I think there is no reliable solution to fulfill your need. I see two things I could implement to allow that : 

1) Add an ID to the inputed model and use it as an unique attribute in the DOM
2) Change the `item-added-to-dom` event to include a reference to related DOM element.

Both methods allow the developer to get a reference to the DOM element that matches a model. Using it's coordinates, this allows to trigger the scroll action. 

This would work only for items already added to the DOM. For those that are in still the buffer or not yet retrieved from the server, there the only solution is to start a scroll loop until the wanted item is added to DOM. 

It's definitely something too specific and too intrusive (on the scroll and on the server) to be implemented into this gallery, but I can implement the tools to provide the DOM when it exists.

**Comment by johtso** [comment]
> First i would like to know which items are currently displayed on the screen

I'm interested in this too.

I'm guessing the only way is to iterate over all elements and check if they are within the current viewport?

If I do this, is there any easy way to get the item data for a given image element?

My use case is that I want to update the url as the user scrolls so that if they refresh the page I can start them where they left off.

**Comment by kfsz** [comment]
@johtso 
collection / visibleCollection both expose both html element reference and image item object  
I'm using this to get first currently visible item (only before reload in my case):
```js
  let visibilityCheck = (rect) => {
      return rect.bottom > 0 && rect.top < window.innerHeight;
  };

  let firstVisibleItemId = "";

  for (const item of naturalGalleryObj.visibleCollection) {
      let boundingClientRect = item._element.getBoundingClientRect();
      if (visibilityCheck(boundingClientRect)) {
          firstVisibleItemId = item.model[getPField()]; // get id field
          break;
      }
  }

  console.log(firstVisibleItemId);
```

just wrote that actually as I went to check what I had there before and realized it didn't work for masonry mode, heh

anyways, I think that should solve the problem of finding image ID?

**Comment by johtso** [comment]
@kfsz that's awesome, thank you! Didn't know item had that `_element` property.

I'm still not completely clear what `visibleCollection` contains. I _think_ it's all elements that have at some point been seen and had their image loaded?

**Comment by kfsz** [comment]
@johtso 

yeah, `visibleCollection` contains all elements visible in the DOM - from start to the bottom of the page   
`collection` additionally contains elements which have been passed to NG via `setItems` / `addItems`, but user has not yet scrolled far enough to display them - basically, when you set 100 images via `setItems` NG will display only like ~30 initially, and as user scrolls down add next ~10, then next ~10, and so on - updating `visibleCollection`   

not exactly sure how many images NG adds at once or when images are exactly added (after scroll) but that's more or less how it works 😃

**Comment by johtso** [comment]
@kfsz thanks for clearing that up for me!

I guess the advantage of finding the elements via the DOM is I can ignore all images that aren't in the first column, saving a lot of iterations if there are a lot of images loaded. Maybe not significant enough to worry about though.

**Comment by kfsz** [comment]
@johtso 

also, hmm, NG emits `pagination` event when it loads new items (and updates `visibleCollection`) - maybe you could update query params then? it won't update when user scrolls up to see previous items, but maybe that would be enough?

and good point about searching first column, `item` also has `last` private property which indicates if it's last item in the row - maybe we could use that, hm - I changed my code to check for that before `getBoundingClientRect()`, which probably doesn't really change anything, but it should be enough for my case.

DOM would be faster, yeah, but hm, you could probably (at least in natural gallery mode) find index of that element in parent div and you should be able to access this element with `naturalGalleryObj.visibleCollection[index]` or add `image.setAttribute('natural-gallery-id', "" + this.model.id);` if you don't mind changing this library's source 😛

**Comment by sambaptista** [comment]
Here's a solution to get items in viewport :

```javascript 
// implement wanted detection here
const isInViewport = (element) => {
  const rect = element.getBoundingClientRect();
  return (
    rect.top >= 0 &&
    rect.left >= 0 &&
    rect.bottom <= window.innerHeight &&
    rect.right <= window.innerWidth
  );
};

// Usage
const viewportCollection = gallery.domCollection.filter(item => isInViewport(item.rootElement));
```
